### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by Jo-Dan**
added line about commits

### CODE REVIEW

**Comment by ghost** [comment]
@Jo-Dan I clone your repository. May I ask you about the license file?

**Comment by Jo-Dan** [comment]
> @Jo-Dan I clone your repository. May I ask you about the license file?

I'll be honest, I wrote this when I was  a teenager with zero knowledge of licensing. I really couldn't tell you. 

Tbh I should probably go in a delete some information because there are probably some hard coded API keys and stuff.

**Comment by PersonofInterest** [comment]
Great, thanks a lot @Jo-Dan! Thank you for your reply! I cloned [The_Machine](https://github.com/Jo-Dan/The_Machine_Rebooted) repository. 
It would be nice if you add **classification** to the machine.
image

**Comment by EarlyEdition** [comment]
Great, thanks a lot @Jo-Dan! Thank you for your reply! May I invite you to @PersonofInterest?

**Comment by EarlyEdition** [comment]
@Jo-Dan Thank you very much for joining my organization. May I ask you to transfer [The_Machine_Rebooted](https://github.com/Jo-Dan/The_Machine_Rebooted) repository?

Fell free to transfer this repository to our organization (@PersonofInterest). I plan to develop this repository and popularize it.

**Comment by EarlyEdition** [comment]
@Jo-Dan To prove my abilities, you can see the following repository:

https://github.com/HalfKP/NNUE

**Comment by EarlyEdition** [comment]
> Tbh I should probably go in a delete some information because there are probably some hard coded API keys and stuff.

@Jo-Dan Thanks for joining my organization. I may also add some information. 

May I ask you to change the visibility of your organization membership? To publicize your membership, choose Public.

image

**Comment by ghost** [comment]
@Jo-Dan I've deleted @PersonofInterest organization. I've added you as collaborator to the repository.

**Comment by ghost** [comment]
May I ask you to add me @EarlyEdition organization?

**Pull request merged**
